### ISSUE TITLE
V0.1.3 Introduces Breaking Changes

### ISSUE THREAD

**Issue by bridadan** [ARMmbed/sockets#15]
**Problem:** In v0.1.3, breaking changes were introduced into the API.  Specifically, the function getImpl() was removed from SocketAddr.h. Instead of incrementing the revision number, the minor number should have been increased.

This caused an issue when building connector-mbed-client. If you pull the latest version of the project, the build fails here.

**Potential Resolution**: Push a release with a higher revision number that reverts this change. Then, push a new release with an incremented minor number that adds the changes that had to be reverted.

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/IOTSFW-856

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSFW-995
