### ISSUE TITLE
TCPAsynch.cpp: Operator usage in destructor doesn't stick to correct type

### ISSUE THREAD

**Issue by adbridge** [ARMmbed/sockets#52]
1. Numerical variables such as _TCPSockets should not be checked for being zero by using the boolean ! operator. Should instead use == 0

2. _tick_handle should be checked for being non-NULL before being used

3. _tick_handle should be reset to NULL rather than 0

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-1601

**Comment by adbridge** [comment]
@bremoran just waiting review I believe/ closing

**Comment by bremoran** [comment]
This issue has been resolved in https://github.com/ARMmbed/sockets/pull/49
